"""PEP 517 backend: setuptools hooks plus public source-archive metadata."""
from __future__ import annotations

import copy
import gzip
from pathlib import Path
import tarfile
import tempfile

from setuptools.build_meta import (
    build_editable,
    build_sdist as _build_sdist,
    build_wheel,
    get_requires_for_build_editable,
    get_requires_for_build_sdist,
    get_requires_for_build_wheel,
    prepare_metadata_for_build_editable,
    prepare_metadata_for_build_wheel,
)


def normalize_sdist(path: Path) -> None:
    """Atomically replace our newly built tar.gz with canonical public headers.

    File bytes, archive names and ordinary permission bits are unchanged. All
    ownership/time metadata is normalized; PAX records are regenerated by tarfile
    only when needed for structural fields such as long or Unicode paths.
    """
    path = Path(path)
    with tempfile.NamedTemporaryFile(dir=path.parent, prefix='.sdist-', suffix='.tmp', delete=False) as output:
        pending = Path(output.name)
        try:
            with tarfile.open(path, 'r:gz') as source:
                with gzip.GzipFile(filename='', mode='wb', fileobj=output, mtime=0) as compressed:
                    with tarfile.open(fileobj=compressed, mode='w', format=tarfile.PAX_FORMAT) as target:
                        for original in source:
                            if not (original.isfile() or original.isdir()) or original.mode & 0o7000:
                                raise ValueError('sdist contains a link, special entry or special permission bits')
                            member = copy.copy(original)
                            member.uid = member.gid = 0
                            member.uname = member.gname = ''
                            member.mtime = 0
                            member.pax_headers = {}
                            payload = source.extractfile(original) if original.isfile() else None
                            try:
                                target.addfile(member, payload)
                            finally:
                                if payload is not None:
                                    payload.close()
            output.flush()
            pending.replace(path)
        finally:
            pending.unlink(missing_ok=True)


def build_sdist(sdist_directory, config_settings=None):
    filename = _build_sdist(sdist_directory, config_settings)
    if not filename.endswith('.tar.gz'):
        raise ValueError('Qingtian source distributions use the reviewed tar.gz format')
    normalize_sdist(Path(sdist_directory) / filename)
    return filename
